[Phi-3dot5-mini-instruct]
    [Phi-3dot5-mini-instruct.metadata]
        owned_by    = 'Microsoft'
        permission  = []
        description = 'Phi-3.5-mini is a lightweight, state-of-the-art open model built upon datasets used for Phi-3 - synthetic data and filtered publicly available websites - with a focus on very high-quality, reasoning dense data. The model belongs to the Phi-3 model family and supports 128K token context length. The model underwent a rigorous enhancement process, incorporating both supervised fine-tuning, proximal policy optimization, and direct preference optimization to ensure precise instruction adherence and robust safety measures.'
    [Phi-3dot5-mini-instruct.network]
        type = 'gRPC'
        url = 'simple-ai-model-00:50051'
[Qwen2-7B-Instruct]
    [Qwen2-7B-Instruct.metadata]
        owned_by    = 'Alibaba Qwen Team'
        permission  = []
        description = 'Qwen2 7B instruct model'
    [Qwen2-7B-Instruct.network]
        type = 'gRPC'
        url = 'simple-ai-model-01:50051'